spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ums
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: always
logging.level:
  org.hibernate.SQL: debug
  org.springframework: info
server:
  servlet:
    session:
      tracking-modes: cookie


